---
- name: Fetch configuration from all webservers
  hosts: all
  tasks:
   - name: Get config
     local_action: get_url dest=configs/{{ ansible_hostname }}.cfg url=http://www.daum.net
#     local_action: get_url dest=configs/{{ ansible_hostname }}.cfg url=http://{{ ansible_hostname }}/index.html
